apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-devops-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-devops
  template:
    metadata:
      labels:
        app: flask-devops
    spec:
      containers:
        - name: flask-container
          image: varun615768/flask-devops-assignment:latest
          ports:
            - containerPort: 8000
