apiVersion: v1
kind: Service
metadata:
  name: flask-devops-service
spec:
  type: NodePort
  selector:
    app: flask-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
